In [26]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.impute import KNNImputer, SimpleImputer
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score

In [6]:
df = pd.read_csv('/content/train.csv') [['Age', 'Pclass', 'Fare', 'Survived']]

In [8]:
df

      Age  Pclass     Fare  Survived
0    22.0       3   7.2500         0
1    38.0       1  71.2833         1
2    26.0       3   7.9250         1
3    35.0       1  53.1000         1
4    35.0       3   8.0500         0
..    ...     ...      ...       ...
886  27.0       2  13.0000         0
887  19.0       1  30.0000         1
888   NaN       3  23.4500         0
889  26.0       1  30.0000         1
890  32.0       3   7.7500         0

[891 rows x 4 columns]

In [10]:
df.isnull().sum()

Age         177
Pclass        0
Fare          0
Survived      0
dtype: int64

In [12]:
df.isnull().mean() * 100

Age         19.86532
Pclass       0.00000
Fare         0.00000
Survived     0.00000
dtype: float64

In [13]:
X = df.drop(columns=['Survived'])
y = df['Survived']

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [17]:
X_train.head()

      Age  Pclass     Fare
331  45.5       1  28.5000
733  23.0       2  13.0000
382  32.0       3   7.9250
704  26.0       3   7.8542
813   6.0       3  31.2750

In [40]:
# knn = KNNImputer(n_neighbors=10, weights='distance')
knn = KNNImputer()

X_train_trf = knn.fit_transform(X_train)
X_test_trf = knn.transform(X_test)

In [41]:
lr = LogisticRegression()

lr.fit(X_train_trf,y_train)

y_pred = lr.predict(X_test_trf)

accuracy_score(y_test,y_pred)

0.7430167597765364

In [42]:
# comarision with simple imputer

si = SimpleImputer()

X_train_trf2 = si.fit_transform(X_train)
X_test_trf2 = si.transform(X_test)

In [43]:
lr = LogisticRegression()

lr.fit(X_train_trf2,y_train)

y_pred = lr.predict(X_test_trf2)

accuracy_score(y_test,y_pred)

0.7374301675977654